### ISSUE TITLE
PHP 7.2 and Nette 2.4

### ISSUE THREAD

**Issue by remicollet** [nette/deprecated#6]
From Fedora QA (with PHP 7.2.0RC6)
https://apps.fedoraproject.org/koschei/package/php-nette-deprecated?collection=f28

I saw that this is fixed in master (dropping relevant files), but for Nette 3.0

For Nette 2.4 we used the following patch
https://src.fedoraproject.org/cgit/rpms/php-nette-deprecated.git/plain/php-nette-deprecated-php72.patch

Perhaps could make sense to apply (btw, I don't see 2.4 branch for this component)

**Comment by remicollet** [comment]
sad way to fix this.

BTW, I prefer to give up trying to do something useful with this Framework, which is now orphaned in Fedora (and will be remove from the repository in the near future)

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/HJ76SXF36A7QUBPQB2SSHSGMULWXX2OI/

**Comment by dg** [comment]
This is a package of obsolete and deprecated code from a Nette Framework that are is developed anymore (mostly 5 years old code). It is not necessary to run a framework. Conversely, the goal is not to use this package at all. It can be useful only for old legacy code.

It is certainly reasonable to remove nette/deprecated from Fedora. But why remove rest of framework, which is fully compatible with 7.2?

**Comment by dg** [comment]
> I just orphaned, because lack of time, lack of interest and lack of upstream collaboration :

I'm sorry, but it really does touch me personally. I've been developing this framework for 10 years, I'm always trying to keep up compatible with the latest PHP releases, I'm doing it myself, I'm doing it for free, I'm doing it as best as I can. 

Can you give me some cases of lack of my collaboration or interest?

**Comment by remicollet** [comment]
The answer to this issue is an example of what frustrate me, like was the nette/tester issue (waiting for 2.0 for months), of this morning updates, nette/application and nette/database test suite failing.

Sorry, but I have really enough work with >500 packages in Fedora, and have to make a choice, and "pleasure" is the most important criteria for "free" time work. I'm very probably more useful when working on the C part (php and its extension)

**Comment by dg** [comment]
But I really do not understand why you want this package, marked as `[discontinued]`, should work under PHP 7.2. 

I appreciate that you are trying to patch this, but this code really only exists for compatibility with the legacy code and it *cannot* be changed.

ad nette/application and nette/database: I think that they are not failing (https://travis-ci.org/nette/application/builds/338037337 and  https://travis-ci.org/nette/database/builds/338037988). 

ad waiting for nette/tester 2.0 for months: What? The previous version worked well. The new one was released when was done.
